export enum BigGoAPIErrorEnum {
  // general error
  ERROR_METHOD = 1,
  WITHOUT_VERIFY = 2,

  // jwt error
  JWT_INVALID = 3,
  JWT_EXPIRED = 4,

  // /video
  VIDEO_UPLOAD_TRANSCODE_ERROR = 1001,
  VIDEO_UPLOAD_VIDEO_EXIST = 1002,
  VIDEO_UPLOAD_PRODUCT_IS_NOT_EXIST = 1008,
  VIDEO_UPLOAD_PRODUCT_LIST_OVER_LIMIT = 1009,
  VIDEO_DIFFERENT_USER = 1003,
  VIDEO_NOT_EXIST = 1004,
  VIDEO_DELETED = 1005,
  VIDEO_PARAMETER_INVALID = 1006,

  // /user
  USER_NOT_EXIST = 1007,
}